services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: diploma-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PaeszEob_2003"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - diploma_sql_data:/var/opt/mssql
    networks:
      - diplomanet

  ml:
    build:
      context: ./AI_ML/PythonMicro
      dockerfile: Dockerfile
    container_name: diet-ml
    ports:
      - "8000:8000"
    networks:
      - diplomanet

  api:
    build:
      context: ./Backend/FitAppBackendRefactor
      dockerfile: FitAppBackendRefactor/Dockerfile
    container_name: diploma-fit-api
    depends_on:
      sql:
        condition: service_started
      ml:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sql,1433;Database=DiplomaFitDb;User Id=sa;Password=PaeszEob_2003;TrustServerCertificate=True;"
      ExternalServices__MlApiBaseUrl: "http://ml:8000"
    ports:
      - "8080:8080"
    networks:
      - diplomanet

  demo-web:
    build:
      context: ./Frontend/diploma-fit-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    container_name: frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "8081:80"
    networks:
      - diplomanet

volumes:
  diploma_sql_data:

networks:
  diplomanet:
    driver: bridge