// <auto-generated />
using System;
using DiplomaFit.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomaFit.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double?>("BodyfatPercent")
                        .HasColumnType("float");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GoalDeltaKg")
                        .HasColumnType("int");

                    b.Property<int>("GoalTimeWeeks")
                        .HasColumnType("int");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<int>("HeightCm")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("CaseId");

                    b.HasIndex("PlanId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.DietPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("int");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<int>("SnacksPerDay")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.ToTable("DietPlans");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultRepsHigh")
                        .HasColumnType("int");

                    b.Property<int>("DefaultRepsLow")
                        .HasColumnType("int");

                    b.Property<int>("DefaultSets")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCompound")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHomeFriendly")
                        .HasColumnType("bit");

                    b.Property<int>("MinExperienceLevel")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameHu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryMuscleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryMuscleSubgroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PushPullCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Food", b =>
                {
                    b.Property<Guid>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CarbsGPer100")
                        .HasColumnType("float");

                    b.Property<double>("FatGPer100")
                        .HasColumnType("float");

                    b.Property<string>("FoodNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodNameHu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KcalPer100")
                        .HasColumnType("float");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProteinGPer100")
                        .HasColumnType("float");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.FoodMealType", b =>
                {
                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "MealType");

                    b.ToTable("FoodMealTypes");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealOrder")
                        .HasColumnType("int");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MealId");

                    b.HasIndex("PlanId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("MealItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("QuantityGrams")
                        .HasColumnType("float");

                    b.HasKey("MealItemId");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Case", b =>
                {
                    b.HasOne("DiplomaFit.Api.Domain.Entities.DietPlan", "Plan")
                        .WithMany("Cases")
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.FoodMealType", b =>
                {
                    b.HasOne("DiplomaFit.Api.Domain.Entities.Food", "Food")
                        .WithMany("MealTypes")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Meal", b =>
                {
                    b.HasOne("DiplomaFit.Api.Domain.Entities.DietPlan", "Plan")
                        .WithMany("Meals")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("DiplomaFit.Api.Domain.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaFit.Api.Domain.Entities.Meal", "Meal")
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.DietPlan", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Food", b =>
                {
                    b.Navigation("MealTypes");
                });

            modelBuilder.Entity("DiplomaFit.Api.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
